import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "./components/navbar"
import Footer from "./components/footer"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <Navbar />
      <main className="container">
        <div className="flex items-start justify-center min-h-screen">
          <div className='mt-20'>{children}</div>
        </div>
      </main>
      <Footer />
    </body>
  </html>
  )
}
